version: '2.17.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx4096m"
      - "discovery.type=single-node"
    volumes:
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
      - /opt/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - "elasticsearch"
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - elastic

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.4.2
  #   depends_on:
  #     - "elasticsearch"
  #     - "kibana"
  #   environment:
  #     setup.kibana.host: kibana:5601
  #     output.elasticsearch.hosts: ["elasticsearch:9200"]
  #   volumes:
  #     - /opt/filebeat:/usr/share/filebeat/filebeat.yml:ro
  #   networks:
  #     - elastic
      
networks:
  elastic:
    driver: bridge
